apiVersion: apps/v1
kind: Deployment
metadata:
  name: horrible-stats
  namespace: horrible-stats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/dcs-analytics-257714/horrible_stats:latest
        ports:
        - containerPort: 80
