FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

COPY requirements.txt /tmp/

RUN apt-get update && \
  apt-get install gcc curl wget -y && \
  pip install --no-cache-dir -r /tmp/requirements.txt && \
  mkdir -p /app/log/ && \
  mkdir -p /app/cache/mission-stats && \
  mkdir -p /app/cache/mission-events && \
  wget https://storage.googleapis.com/pub/gsutil.tar.gz && \
  tar xfz gsutil.tar.gz -C $HOME && \
  rm gsutil.tar.gz && \
  echo "PATH=${PATH}:$HOME/gsutil" >> /root/.bashrc
