FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

RUN pip install --no-cache-dir -r /tmp/requirements.txt
WORKDIR "/app/"
COPY dev/ /var/dev/
COPY requirements.txt /tmp/
RUN mkdir /app/horrible/