# apiVersion: cert-manager.io/v1alpha2
# kind: Issuer
# metadata:
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: horrible-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'mcdelaney@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: dcs-analytics-257714
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ahorribleserver-com
  namespace: horrible-stats
spec:
  secretName: horribleserver-tls
  issuerRef:
    # The issuer created previously
    name: horrible-issuer
  dnsNames:
  - ahorribleserver.com
  - www.ahorribleserver.com
